In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings(action="ignore")
import pandas_profiling

In [2]:
raw_data1 = pd.read_excel("./Participants Data/Data_Train.xlsx")
test_data = pd.read_excel("./Participants Data/Data_Test.xlsx")
raw_data1['source'] = 'train'
test_data['source'] = 'test'
raw_data = pd.concat([raw_data1,test_data],ignore_index=True)

In [3]:
raw_data1.head(5)

,Restaurant,Location,Cuisines,Average_Cost,Minimum_Order,Rating,Votes,Reviews,Delivery_Time,source
0,ID_6321,"FTI College, Law College Road, Pune","Fast Food, Rolls, Burger, Salad, Wraps",₹200,₹50,3.5,12,4,30 minutes,train
1,ID_2882,"Sector 3, Marathalli","Ice Cream, Desserts",₹100,₹50,3.5,11,4,30 minutes,train
2,ID_1595,Mumbai Central,"Italian, Street Food, Fast Food",₹150,₹50,3.6,99,30,65 minutes,train
3,ID_5929,"Sector 1, Noida","Mughlai, North Indian, Chinese",₹250,₹99,3.7,176,95,30 minutes,train
4,ID_6123,"Rmz Centennial, I Gate, Whitefield","Cafe, Beverages",₹200,₹99,3.2,521,235,65 minutes,train

In [4]:
raw_data1['Rating'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
raw_data1['Votes'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

raw_data1['Average_Cost'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
raw_data1['Minimum_Order'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

raw_data1['Reviews'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

raw_data1['Rating'] = pd.to_numeric(raw_data1['Rating'])
raw_data1['Votes'] = pd.to_numeric(raw_data1['Votes'])

raw_data1['Average_Cost'] = pd.to_numeric(raw_data1['Average_Cost'])
raw_data1['Minimum_Order'] = pd.to_numeric(raw_data1['Minimum_Order'])

raw_data1['Reviews'] = pd.to_numeric(raw_data1['Reviews'])

In [5]:
pandas_profiling.ProfileReport(raw_data1)

In [6]:
def comma_seprated_categories(df, col):
    cols = list(df[col])
    max = 1
    for i in cols:
        if len(i.split(',')) > max:
            max = len(i.split(','))
    print("Max number of",col,"in a cell",max)
    
    all_cats = []
    for i in cols :
     if len(i.split(',')) == 1:
         all_cats.append(i.split(',')[0].strip().upper())
     else :
        for it in range(len(i.split(','))):
            all_cats.append(i.split(',')[it].strip().upper())
    print("\n\nNumber of Unique",col,": ", len(pd.Series(all_cats).unique()))
    print("\n\nUnique",col,":\n", pd.Series(all_cats).unique()) 
    return list(pd.Series(all_cats).unique())

In [7]:
raw_data1 = raw_data1.dropna()

In [8]:
raw_data1['Cuisines'] = raw_data1['Cuisines'].str.upper()
raw_data1['Cuisines'] = raw_data1['Cuisines'].str.strip()

In [9]:
all_cusines = comma_seprated_categories(raw_data1,col='Cuisines')

Max number of Cuisines in a cell 8


Number of Unique Cuisines :  100


Unique Cuisines :
 ['FAST FOOD' 'ROLLS' 'BURGER' 'SALAD' 'WRAPS' 'ICE CREAM' 'DESSERTS'
 'ITALIAN' 'STREET FOOD' 'MUGHLAI' 'NORTH INDIAN' 'CHINESE' 'CAFE'
 'BEVERAGES' 'SOUTH INDIAN' 'THAI' 'ASIAN' 'MITHAI' 'MOMOS' 'INDONESIAN'
 'BIRYANI' 'MEXICAN' 'JAPANESE' 'BAKERY' 'BURMESE' 'BUBBLE TEA' 'TEA'
 'PIZZA' 'MANGALOREAN' 'EUROPEAN' 'CONTINENTAL' 'SANDWICH' 'HEALTHY FOOD'
 'BENGALI' 'AMERICAN' 'MISHTI' 'ANDHRA' 'LUCKNOWI' 'GERMAN' 'ARABIAN'
 'FINGER FOOD' 'KEBAB' 'CHETTINAD' 'SEAFOOD' 'JUICES' 'PARSI' 'SUSHI'
 'ODIA' 'TAMIL' 'CANTONESE' 'MAHARASHTRIAN' 'TIBETAN' 'HYDERABADI'
 'LEBANESE' 'SPANISH' 'BAR FOOD' 'KONKAN' 'NORTH EASTERN' 'STEAK' 'PAAN'
 'MEDITERRANEAN' 'BOHRI' 'AFGHAN' 'KERALA' 'GUJARATI' 'BBQ' 'RAW MEATS'
 'MALAYSIAN' 'VIETNAMESE' 'SRI LANKAN' 'RAJASTHANI' 'POKÉ' 'GOAN'
 'BRAZILIAN' 'BELGIAN' 'NAGA' 'KOREAN' 'MODERN INDIAN' 'KASHMIRI' 'FRENCH'
 'PORTUGUESE' 'CHARCOAL CHICKEN' 'AWADHI' 'FROZEN YOGURT' 'BANGLADESHI'
 'COFFEE' 'BIHARI' 'MALWANI' 'IRANIAN' 'NEPALESE' 'INDIAN' 'TEX-MEX'
 'HOT DOGS' 'SOUTH AMERICAN' 'ROAST CHICKEN' 'MIDDLE EASTERN' 'AFRICAN'
 'TURKISH' 'ASSAMESE' 'GREEK']

In [10]:
raw_data1['Cuisines_1'] = raw_data1['Cuisines'].str.split(",",expand = True)[0]
raw_data1['Cuisines_2'] = raw_data1['Cuisines'].str.split(",",expand = True)[1]
raw_data1['Cuisines_3'] = raw_data1['Cuisines'].str.split(",",expand = True)[2]
raw_data1['Cuisines_4'] = raw_data1['Cuisines'].str.split(",",expand = True)[3]
raw_data1['Cuisines_5'] = raw_data1['Cuisines'].str.split(",",expand = True)[4]
raw_data1['Cuisines_6'] = raw_data1['Cuisines'].str.split(",",expand = True)[5]
raw_data1['Cuisines_7'] = raw_data1['Cuisines'].str.split(",",expand = True)[6]
raw_data1['Cuisines_8'] = raw_data1['Cuisines'].str.split(",",expand = True)[7]

In [11]:
raw_data1.drop(['Cuisines','Restaurant'],inplace=True,axis=1)

In [12]:
all_locations = []
for i in raw_data1['Location'].value_counts().items():
    print(i[0])
    all_locations.append(i[0].strip())

Mico Layout, Stage 2, BTM Layout,Bangalore
D-Block, Sector 63, Noida
Sector 1, Noida
FTI College, Law College Road, Pune
Delhi University-GTB Nagar
Sector 14, Noida
Mumbai Central
Delhi Administration Flats, Timarpur
Rmz Centennial, I Gate, Whitefield
Laxman Vihar Industrial Area, Sector 3A, Gurgoan
Delhi High Court, India Gate
MG Road, Pune
Sandhurst Road, Mumbai CST Area
Nathan Road, Mangaldas Road, Pune
Sector 3, Marathalli
Majestic
Yerawada, Pune, Maharashtra
Dockyard Road, Mumbai CST Area
Delhi Cantt.
Pune University
Sector 63A,Gurgaon
Babarpur, New Delhi, Delhi
Moulali, Kolkata
Chandni Chowk, Kolkata
Raja Bazar, Kolkata
Tiretti, Kolkata
Hyderabad Public School, Begumpet
Tejas Nagar Colony, Wadala West, Mumbai
Noorkhan Bazaar, Malakpet, Hyderabad
Musi Nagar, Malakpet, Hyderabad
Gora Bazar, Rajbari, North Dumdum, Kolkata
Panjetan Colony, Malakpet, Hyderabad
Chatta Bazaar, Malakpet, Hyderabad
Jaya Nagar, Saidabad, Hyderabad
BTM Layout 1, Electronic City

In [13]:
print(len(raw_data['Location'].str.split(",",expand = True)[0].value_counts()))

35

In [14]:
def comma_split(a):
    if a.count("-") == 1:
        return a.split(",")[0]
    else:
        return ",".join(a.split(",", 2)[:2])

In [15]:
a = comma_split(raw_data1['Location'].loc[10])
print(a)

Mumbai Central

In [16]:
print(all_locations)
print("\n\n")
print(all_cusines)

['Mico Layout, Stage 2, BTM Layout,Bangalore', 'D-Block, Sector 63, Noida', 'Sector 1, Noida', 'FTI College, Law College Road, Pune', 'Delhi University-GTB Nagar', 'Sector 14, Noida', 'Mumbai Central', 'Delhi Administration Flats, Timarpur', 'Rmz Centennial, I Gate, Whitefield', 'Laxman Vihar Industrial Area, Sector 3A, Gurgoan', 'Delhi High Court, India Gate', 'MG Road, Pune', 'Sandhurst Road, Mumbai CST Area', 'Nathan Road, Mangaldas Road, Pune', 'Sector 3, Marathalli', 'Majestic', 'Yerawada, Pune, Maharashtra', 'Dockyard Road, Mumbai CST Area', 'Delhi Cantt.', 'Pune University', 'Sector 63A,Gurgaon', 'Babarpur, New Delhi, Delhi', 'Moulali, Kolkata', 'Chandni Chowk, Kolkata', 'Raja Bazar, Kolkata', 'Tiretti, Kolkata', 'Hyderabad Public School, Begumpet', 'Tejas Nagar Colony, Wadala West, Mumbai', 'Noorkhan Bazaar, Malakpet, Hyderabad', 'Musi Nagar, Malakpet, Hyderabad', 'Gora Bazar, Rajbari, North Dumdum, Kolkata', 'Panjetan Colony, Malakpet, Hyderabad', 'Chatta Bazaar, Malakpet, Hyderabad', 'Jaya Nagar, Saidabad, Hyderabad', 'BTM Layout 1, Electronic City']



['FAST FOOD', 'ROLLS', 'BURGER', 'SALAD', 'WRAPS', 'ICE CREAM', 'DESSERTS', 'ITALIAN', 'STREET FOOD', 'MUGHLAI', 'NORTH INDIAN', 'CHINESE', 'CAFE', 'BEVERAGES', 'SOUTH INDIAN', 'THAI', 'ASIAN', 'MITHAI', 'MOMOS', 'INDONESIAN', 'BIRYANI', 'MEXICAN', 'JAPANESE', 'BAKERY', 'BURMESE', 'BUBBLE TEA', 'TEA', 'PIZZA', 'MANGALOREAN', 'EUROPEAN', 'CONTINENTAL', 'SANDWICH', 'HEALTHY FOOD', 'BENGALI', 'AMERICAN', 'MISHTI', 'ANDHRA', 'LUCKNOWI', 'GERMAN', 'ARABIAN', 'FINGER FOOD', 'KEBAB', 'CHETTINAD', 'SEAFOOD', 'JUICES', 'PARSI', 'SUSHI', 'ODIA', 'TAMIL', 'CANTONESE', 'MAHARASHTRIAN', 'TIBETAN', 'HYDERABADI', 'LEBANESE', 'SPANISH', 'BAR FOOD', 'KONKAN', 'NORTH EASTERN', 'STEAK', 'PAAN', 'MEDITERRANEAN', 'BOHRI', 'AFGHAN', 'KERALA', 'GUJARATI', 'BBQ', 'RAW MEATS', 'MALAYSIAN', 'VIETNAMESE', 'SRI LANKAN', 'RAJASTHANI', 'POKÉ', 'GOAN', 'BRAZILIAN', 'BELGIAN', 'NAGA', 'KOREAN', 'MODERN INDIAN', 'KASHMIRI', 'FRENCH', 'PORTUGUESE', 'CHARCOAL CHICKEN', 'AWADHI', 'FROZEN YOGURT', 'BANGLADESHI', 'COFFEE', 'BIHARI', 'MALWANI', 'IRANIAN', 'NEPALESE', 'INDIAN', 'TEX-MEX', 'HOT DOGS', 'SOUTH AMERICAN', 'ROAST CHICKEN', 'MIDDLE EASTERN', 'AFRICAN', 'TURKISH', 'ASSAMESE', 'GREEK']

In [17]:
raw_data1.head()

,Location,Average_Cost,Minimum_Order,Rating,Votes,Reviews,Delivery_Time,source,Cuisines_1,Cuisines_2,Cuisines_3,Cuisines_4,Cuisines_5,Cuisines_6,Cuisines_7,Cuisines_8
0,"FTI College, Law College Road, Pune",200.0,50,35.0,12.0,4.0,30 minutes,train,FAST FOOD,ROLLS,BURGER,SALAD,WRAPS,None,None,None
1,"Sector 3, Marathalli",100.0,50,35.0,11.0,4.0,30 minutes,train,ICE CREAM,DESSERTS,None,None,None,None,None,None
2,Mumbai Central,150.0,50,36.0,99.0,30.0,65 minutes,train,ITALIAN,STREET FOOD,FAST FOOD,None,None,None,None,None
3,"Sector 1, Noida",250.0,99,37.0,176.0,95.0,30 minutes,train,MUGHLAI,NORTH INDIAN,CHINESE,None,None,None,None,None
4,"Rmz Centennial, I Gate, Whitefield",200.0,99,32.0,521.0,235.0,65 minutes,train,CAFE,BEVERAGES,None,None,None,None,None,None

In [18]:
cus_list = []
for i in range(1,9):
    i = str(i)
    cus_list.append("Cuisines_"+i)

In [19]:
cus_list

['Cuisines_1',
 'Cuisines_2',
 'Cuisines_3',
 'Cuisines_4',
 'Cuisines_5',
 'Cuisines_6',
 'Cuisines_7',
 'Cuisines_8']

In [20]:
for i in cus_list:
    raw_data1[i].fillna("NAA", inplace=True)
all_cusines.append("NAA")

In [21]:
from sklearn.preprocessing import LabelEncoder



le_cuisines = LabelEncoder()
le_locality = LabelEncoder()


le_locality.fit(all_locations)
le_cuisines.fit(all_cusines)

LabelEncoder()

In [22]:
all_cusines.append('None')

In [23]:
le_locality.inverse_transform([8])

array(['Delhi University-GTB Nagar'], dtype='<U48')

In [24]:
raw_data1['Location_Encoded'] = le_locality.transform(raw_data1['Location'])

In [25]:
raw_data1['Cuisines_1'] = le_cuisines.transform(raw_data1['Cuisines_1'].str.strip())
raw_data1['Cuisines_2'] = le_cuisines.transform(raw_data1['Cuisines_2'].str.strip())
raw_data1['Cuisines_3'] = le_cuisines.transform(raw_data1['Cuisines_3'].str.strip())
raw_data1['Cuisines_4'] = le_cuisines.transform(raw_data1['Cuisines_4'].str.strip())
raw_data1['Cuisines_5'] = le_cuisines.transform(raw_data1['Cuisines_5'].str.strip())
raw_data1['Cuisines_6'] = le_cuisines.transform(raw_data1['Cuisines_6'].str.strip())
raw_data1['Cuisines_7'] = le_cuisines.transform(raw_data1['Cuisines_7'].str.strip())
raw_data1['Cuisines_8'] = le_cuisines.transform(raw_data1['Cuisines_8'].str.strip())

In [26]:
raw_data1

,Location,Average_Cost,Minimum_Order,Rating,Votes,Reviews,Delivery_Time,source,Cuisines_1,Cuisines_2,Cuisines_3,Cuisines_4,Cuisines_5,Cuisines_6,Cuisines_7,Cuisines_8,Location_Encoded
0,"FTI College, Law College Road, Pune",200.0,50,35.0,12.0,4.0,30 minutes,train,31,82,20,83,100,68,68,68,10
1,"Sector 3, Marathalli",100.0,50,35.0,11.0,4.0,30 minutes,train,42,29,68,68,68,68,68,68,30
2,Mumbai Central,150.0,50,36.0,99.0,30.0,65 minutes,train,46,91,31,68,68,68,68,68,19
3,"Sector 1, Noida",250.0,99,37.0,176.0,95.0,30 minutes,train,67,72,26,68,68,68,68,68,28
4,"Rmz Centennial, I Gate, Whitefield",200.0,99,32.0,521.0,235.0,65 minutes,train,22,14,68,68,68,68,68,68,26
5,"Rmz Centennial, I Gate, Whitefield",150.0,50,38.0,46.0,18.0,30 minutes,train,87,72,26,68,68,68,68,68,26
6,Mumbai Central,150.0,50,37.0,108.0,31.0,30 minutes,train,14,31,68,68,68,68,68,68,19
7,Delhi University-GTB Nagar,650.0,50,40.0,1731.0,1235.0,45 minutes,train,26,96,5,68,68,68,68,68,8
8,Delhi University-GTB Nagar,100.0,50,39.0,110.0,26.0,30 minutes,train,64,91,68,68,68,68,68,68,8
9,"Sector 1, Noida",200.0,50,39.0,562.0,294.0,65 minutes,train,31,72,82,26,66,67,68,68,28
10,Mumbai Central,350.0,50,38.0,186.0,61.0,30 minutes,train,72,26,67,68,68,68,68,68,19
11,"Yerawada, Pune, Maharashtra",800.0,50,42.0,1693.0,1239.0,45 minutes,train,26,96,44,46,68,68,68,68,34
13,Delhi University-GTB Nagar,50.0,0,38.0,184.0,128.0,45 minutes,train,14,68,68,68,68,68,68,68,8
14,"Delhi Administration Flats, Timarpur",100.0,50,35.0,23.0,5.0,30 minutes,train,31,68,68,68,68,68,68,68,5
15,"Moulali, Kolkata",100.0,50,36.0,353.0,53.0,30 minutes,train,16,67,68,68,68,68,68,68,18
17,"Dockyard Road, Mumbai CST Area",200.0,50,37.0,139.0,47.0,30 minutes,train,26,72,87,31,68,68,68,68,9
19,"Gora Bazar, Rajbari, North Dumdum, Kolkata",100.0,50,37.0,159.0,46.0,30 minutes,train,87,68,68,68,68,68,68,68,11
20,"D-Block, Sector 63, Noida",200.0,99,28.0,67.0,23.0,45 minutes,train,26,72,82,66,68,68,68,68,4
21,"Sector 14, Noida",150.0,50,39.0,387.0,160.0,45 minutes,train,72,82,68,68,68,68,68,68,29
22,"D-Block, Sector 63, Noida",250.0,50,30.0,5.0,2.0,30 minutes,train,72,26,68,68,68,68,68,68,4
23,"D-Block, Sector 63, Noida",200.0,99,37.0,138.0,26.0,65 minutes,train,16,72,68,68,68,68,68,68,4
24,"Sector 3, Marathalli",150.0,50,32.0,4.0,1.0,30 minutes,train,72,26,31,68,68,68,68,68,30
26,"D-Block, Sector 63, Noida",100.0,99,37.0,110.0,38.0,45 minutes,train,72,26,68,68,68,68,68,68,4
27,Mumbai Central,150.0,50,32.0,15.0,9.0,45 minutes,train,31,87,91,68,68,68,68,68,19
28,"Dockyard Road, Mumbai CST Area",150.0,50,33.0,44.0,19.0,45 minutes,train,72,68,68,68,68,68,68,68,9
29,"Sector 1, Noida",200.0,50,38.0,18.0,18.0,30 minutes,train,72,26,68,68,68,68,68,68,28
30,"Gora Bazar, Rajbari, North Dumdum, Kolkata",150.0,50,32.0,18.0,7.0,30 minutes,train,72,68,68,68,68,68,68,68,11
31,"D-Block, Sector 63, Noida",400.0,50,40.0,189.0,132.0,30 minutes,train,22,61,47,46,26,68,68,68,4
32,"FTI College, Law College Road, Pune",200.0,50,31.0,279.0,74.0,45 minutes,train,8,31,82,14,68,68,68,68,10
33,"D-Block, Sector 63, Noida",350.0,99,33.0,22.0,13.0,45 minutes,train,72,26,68,68,68,68,68,68,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11058,Mumbai Central,150.0,50,37.0,81.0,22.0,30 minutes,train,14,29,68,68,68,68,68,68,19
11059,Pune University,250.0,50,36.0,114.0,50.0,45 minutes,train,22,14,84,31,68,68,68,68,24
11061,"Chatta Bazaar, Malakpet, Hyderabad",100.0,50,35.0,18.0,7.0,30 minutes,train,87,14,68,68,68,68,68,68,3
11062,"Sector 1, Noida",300.0,0,37.0,142.0,72.0,45 minutes,train,26,31,14,68,68,68,68,68,28
11063,"Musi Nagar, Malakpet, Hyderabad",200.0,50,34.0,148.0,25.0,45 minutes,train,72,26,16,68,68,68,68,68,20
11064,Delhi Cantt.,200.0,50,45.0,1297.0,549.0,45 minutes,train,72,67,68,68,68,68,68,68,6
11065,"Musi Nagar, Malakpet, Hyderabad",100.0,50,28.0,4.0,3.0,30 minutes,train,72,14,68,68,68,68,68,68,20
11066,"Babarpur, New Delhi, Delhi",100.0,50,27.0,4.0,1.0,30 minutes,train,72,26,68,68,68,68,68,68,1
11067,"Chatta Bazaar, Malakpet, Hyderabad",350.0,50,34.0,18.0,4.0,30 minutes,train,87,72,26,68,68,68,68,68,3
11068,Delhi University-GTB Nagar,100.0,50,28.0,8.0,3.0,30 minutes,train,31,68,68,68,68,68,68,68,8
11069,"Delhi Administration Flats, Timarpur",300.0,50,34.0,13.0,4.0,65 minutes,train,72,26,68,68,68,68,68,68,5
11070,"Sector 1, Noida",200.0,0,37.0,260.0,77.0,65 minutes,train,72,26,68,68,68,68,68,68,28
11071,"Mico Layout, Stage 2, BTM Layout,Bangalore",200.0,50,36.0,24.0,3.0,30 minutes,train,72,26,68,68,68,68,68,68,17
11072,Delhi University-GTB Nagar,100.0,50,38.0,80.0,38.0,30 minutes,train,31,82,68,68,68,68,68,68,8
11073,"Nathan Road, Mangaldas Road, Pune",300.0,50,38.0,689.0,341.0,45 minutes,train,72,67,50,26,68,68,68,68,21
11074,"Musi Nagar, Malakpet, Hyderabad",100.0,50,30.0,6.0,1.0,30 minutes,train,87,68,68,68,68,68,68,68,20
11075,"Mico Layout, Stage 2, BTM Layout,Bangalore",100.0,50,32.0,6.0,4.0,30 minutes,train,14,48,68,68,68,68,68,68,17
11076,"D-Block, Sector 63, Noida",350.0,50,34.0,132.0,47.0,45 minutes,train,72,67,68,68,68,68,68,68,4
11077,"Sector 14, Noida",100.0,50,32.0,7.0,3.0,30 minutes,train,14,94,27,72,68,68,68,68,29
11078,"Raja Bazar, Kolkata",100.0,50,34.0,163.0,24.0,30 minutes,train,79,31,63,68,68,68,68,68,25
11079,"Delhi Administration Flats, Timarpur",100.0,50,36.0,57.0,12.0,30 minutes,train,72,68,68,68,68,68,68,68,5
11080,"Sector 1, Noida",650.0,50,40.0,715.0,422.0,65 minutes,train,26,85,5,72,68,68,68,68,28
11081,Delhi University-GTB Nagar,150.0,50,36.0,38.0,21.0,30 minutes,train,31,29,68,68,68,68,68,68,8
11083,"Nathan Road, Mangaldas Road, Pune",400.0,50,43.0,1741.0,736.0,30 minutes,train,26,87,31,72,68,68,68,68,21
11087,"Dockyard Road, Mumbai CST Area",200.0,50,35.0,63.0,34.0,30 minutes,train,26,67,72,68,68,68,68,68,9
11088,"Rmz Centennial, I Gate, Whitefield",150.0,50,36.0,56.0,18.0,30 minutes,train,72,26,16,68,68,68,68,68,26
11089,"BTM Layout 1, Electronic City",250.0,50,42.0,326.0,189.0,30 minutes,train,97,26,28,66,68,68,68,68,0
11090,"Sector 14, Noida",100.0,50,36.0,36.0,16.0,30 minutes,train,31,68,68,68,68,68,68,68,29
11091,Majestic,100.0,50,35.0,45.0,18.0,30 minutes,train,87,26,72,68,68,68,68,68,16
11092,"Sector 3, Marathalli",100.0,50,31.0,24.0,9.0,30 minutes,train,72,68,68,68,68,68,68,68,30

In [27]:
raw_data1.drop(['Location'],inplace=True,axis=1)

Average_Cost        float64
Minimum_Order         int64
Rating              float64
Votes               float64
Reviews             float64
Delivery_Time        object
source               object
Cuisines_1            int64
Cuisines_2            int64
Cuisines_3            int64
Cuisines_4            int64
Cuisines_5            int64
Cuisines_6            int64
Cuisines_7            int64
Cuisines_8            int64
Location_Encoded      int64
dtype: object